version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - "milescsmith"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    assignees:
      - "milescsmith"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    assignees:
      - "milescsmith"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - "milescsmith"
