# .github/workflows/coverage.yml
name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install nox==2021.10.1
    - run: pip install poetry==1.1.11
    - run: pip install nox-poetry==0.9.0
    - run: nox --sessions tests-3.9 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
